# docker-compose.yml
version: '3.8'
services:
  control-m-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=50MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=50MB
      - TESSDATA_PREFIX=/usr/share/tessdata
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.xml
    depends_on:
      - control_m_db
    networks:
      - control-m-network
    volumes:
      - ./test-pdfs:/app/test-pdfs
      - ./pdfs:/app/pdfs
      - storage-data:/app/storage
    deploy:
      resources:
        limits:
          memory: 2G


  control_m_db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - control-m-network

volumes:
  db-data:
  storage-data:

networks:
  control-m-network:
    driver: bridge
