spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  jackson:
    time-zone: Europe/Moscow


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
app:
  base-url: http://localhost:8080
  qr-code:
    directory: ./qr-codes

server:
  port: 8080
  address: 0.0.0.0

test:
  input:
    dir: ./test-pdfs
  client-id: 1


protocol:
  template:
    path: /app/templates/protocol_template.xlsx   # путь к шаблону внутри контейнера
  mapping:
    fields:
      - sourceColumnName: "Наименование конструкции"
        sheetName: "Лист1"
        cellReference: "B2"
      - sourceColumnName: "Класс бетона"
        sheetName: "Лист1"
        cellReference: "C5"
      - sourceColumnName: "Дата заливки"
        sheetName: "Лист1"
        cellReference: "D7"